language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --system --deploy
  - pipenv install --dev --system --deploy
services:
  - postgresql
before_script:
  - psql -c 'create database rses;' -U postgres
  - psql -f database/create.sql -U postgres -d rses
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/rses/src
script:
  - pytest tests